<?php
if ( !defined( 'ABSPATH' ) ) exit;
if( function_exists('acf_add_local_field_group') ):

    acf_add_local_field_group(array(
        'key' => 'group_60634f9522825',
        'title' => '比比爱书者设置',
        'fields' => array(
            array(
                'key' => 'field_60634fe0ff2a0',
                'label' => '菜单设置',
                'name' => '',
                'type' => 'tab',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'placement' => 'top',
                'endpoint' => 0,
            ),
            array(
                'key' => 'field_60689a77768f5',
                'label' => '底部通用导航',
                'name' => 'bee_setting_tabbar',
                'type' => 'group',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'layout' => 'row',
                'acfe_seamless_style' => 0,
                'acfe_group_modal' => 0,
                'sub_fields' => array(
                    array(
                        'key' => 'field_60689abd768f6',
                        'label' => '菜单项样式',
                        'name' => 'menu_style',
                        'type' => 'radio',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'choices' => array(
                            1 => '仅图标',
                            2 => '图标+文字',
                        ),
                        'allow_null' => 0,
                        'other_choice' => 0,
                        'default_value' => 1,
                        'layout' => 'horizontal',
                        'return_format' => 'value',
                        'save_other_choice' => 0,
                    ),
                    array(
                        'key' => 'field_60689f012fd37',
                        'label' => '菜单项文字',
                        'name' => 'menu_text',
                        'type' => 'text',
                        'instructions' => '四个菜单中间用,隔开',
                        'required' => 0,
                        'conditional_logic' => array(
                            array(
                                array(
                                    'field' => 'field_60689abd768f6',
                                    'operator' => '==',
                                    'value' => '2',
                                ),
                            ),
                        ),
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '首页,发现,资讯,我的',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                    ),
                    array(
                        'key' => 'field_60689b1c768f7',
                        'label' => '更多菜单按钮',
                        'name' => 'menu_more_show',
                        'type' => 'true_false',
                        'instructions' => '',
                        'required' => 1,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'message' => '',
                        'default_value' => 1,
                        'ui' => 1,
                        'ui_on_text' => '显示',
                        'ui_off_text' => '隐藏',
                    ),
                    array(
                        'key' => 'field_6068a01229dd5',
                        'label' => '更多菜单选项',
                        'name' => 'menu_more_list',
                        'type' => 'repeater',
                        'instructions' => '可自定义菜单标题，拖动菜单位置顺序。',
                        'required' => 0,
                        'conditional_logic' => array(
                            array(
                                array(
                                    'field' => 'field_60689b1c768f7',
                                    'operator' => '==',
                                    'value' => '1',
                                ),
                            ),
                        ),
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'acfe_repeater_stylised_button' => 0,
                        'collapsed' => '',
                        'min' => 1,
                        'max' => 4,
                        'layout' => 'table',
                        'button_label' => '添加新菜单',
                        'sub_fields' => array(
                            array(
                                'key' => 'field_6068a01229dd6',
                                'label' => '菜单项标题',
                                'name' => 'menu_title',
                                'type' => 'text',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '20',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'default_value' => '',
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                                'maxlength' => '',
                            ),
                            array(
                                'key' => 'field_6068a34c0b97f',
                                'label' => '菜单项图标',
                                'name' => 'menu_icon',
                                'type' => 'image',
                                'instructions' => '100x100px',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '10',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'uploader' => '',
                                'acfe_thumbnail' => 0,
                                'return_format' => 'url',
                                'preview_size' => 'thumbnail',
                                'min_width' => '',
                                'min_height' => '',
                                'min_size' => '',
                                'max_width' => 100,
                                'max_height' => 100,
                                'max_size' => '',
                                'mime_types' => '',
                                'library' => 'all',
                            ),
                            array(
                                'key' => 'field_6068a01229dd7',
                                'label' => '菜单对应内容',
                                'name' => 'menu_posttype',
                                'type' => 'select',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'choices' => array(
                                    '##内置功能' => '##内置功能',
                                    'beebee_mode_kf' => '客服',
                                    '##自定义跳转' => '##自定义跳转',
                                    'beebee_mode_custom_img' => '弹出图片',
                                    'beebee_mode_custom_link' => '跳转页面',
                                    'beebee_mode_custom_wx' => '跳转小程序',
                                ),
                                'default_value' => false,
                                'allow_null' => 0,
                                'multiple' => 0,
                                'ui' => 0,
                                'return_format' => 'value',
                                'ajax' => 0,
                                'placeholder' => '',
                            ),
                            array(
                                'key' => 'field_6068a4060b980',
                                'label' => '跳转AppID',
                                'name' => 'menu_custom_appid',
                                'type' => 'text',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => array(
                                    array(
                                        array(
                                            'field' => 'field_6068a01229dd7',
                                            'operator' => '==',
                                            'value' => 'beebee_mode_custom_wx',
                                        ),
                                    ),
                                ),
                                'wrapper' => array(
                                    'width' => '10',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'default_value' => '',
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                                'maxlength' => '',
                            ),
                            array(
                                'key' => 'field_6068a25c0b97e',
                                'label' => '跳转path',
                                'name' => 'menu_custom_link',
                                'type' => 'text',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => array(
                                    array(
                                        array(
                                            'field' => 'field_6068a01229dd7',
                                            'operator' => '==',
                                            'value' => 'beebee_mode_custom_link',
                                        ),
                                    ),
                                    array(
                                        array(
                                            'field' => 'field_6068a01229dd7',
                                            'operator' => '==',
                                            'value' => 'beebee_mode_custom_wx',
                                        ),
                                    ),
                                ),
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'default_value' => '',
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                                'maxlength' => '',
                            ),
                            array(
                                'key' => 'field_6068aba0980a9',
                                'label' => '弹出图片',
                                'name' => 'menu_custom_img',
                                'type' => 'image',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => array(
                                    array(
                                        array(
                                            'field' => 'field_6068a01229dd7',
                                            'operator' => '==',
                                            'value' => 'beebee_mode_custom_img',
                                        ),
                                    ),
                                ),
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'uploader' => '',
                                'acfe_thumbnail' => 0,
                                'return_format' => 'url',
                                'preview_size' => 'medium',
                                'min_width' => '',
                                'min_height' => '',
                                'min_size' => '',
                                'max_width' => '',
                                'max_height' => '',
                                'max_size' => '',
                                'mime_types' => '',
                                'library' => 'all',
                            ),
                        ),
                    ),
                ),
            ),
            array(
                'key' => 'field_6063542d043ed',
                'label' => '首页头部菜单',
                'name' => 'bee_setting_homemenu',
                'type' => 'repeater',
                'instructions' => '可自定义菜单标题，拖动菜单位置顺序。菜单项最少1个，最多10个',
                'required' => 1,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'acfe_repeater_stylised_button' => 0,
                'collapsed' => '',
                'min' => 1,
                'max' => 10,
                'layout' => 'table',
                'button_label' => '添加新菜单',
                'sub_fields' => array(
                    array(
                        'key' => 'field_606888f9df6ca',
                        'label' => '菜单项标题',
                        'name' => 'menu_title',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '20',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                    ),
                    array(
                        'key' => 'field_60635455043ee',
                        'label' => '菜单对应内容',
                        'name' => 'menu_posttype',
                        'type' => 'select',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'choices' => array(
                            '## 文章类型' => '## 文章类型',
                            'beebee_topic' => '专题列表',
                            'beebee_library' => '书目列表',
                            'beebee_quot' => '语录列表',
                            '## 文章类别' => '## 文章类别',
                            'beebee_library_state' => '书目状态',
                            'beebee_library_cats' => '书目分类',
                        ),
                        'default_value' => false,
                        'allow_null' => 0,
                        'multiple' => 0,
                        'ui' => 0,
                        'return_format' => 'value',
                        'ajax' => 0,
                        'placeholder' => '',
                    ),
                    array(
                        'key' => 'field_60688992df6cb',
                        'label' => '书目分类',
                        'name' => 'menu_libcats_id',
                        'type' => 'taxonomy',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => array(
                            array(
                                array(
                                    'field' => 'field_60635455043ee',
                                    'operator' => '==',
                                    'value' => 'beebee_library_cats',
                                ),
                            ),
                        ),
                        'wrapper' => array(
                            'width' => '15',
                            'class' => '',
                            'id' => '',
                        ),
                        'taxonomy' => 'beebee_library_cats',
                        'field_type' => 'select',
                        'allow_null' => 0,
                        'add_term' => 0,
                        'save_terms' => 0,
                        'load_terms' => 0,
                        'return_format' => 'id',
                        'acfe_bidirectional' => array(
                            'acfe_bidirectional_enabled' => '0',
                        ),
                        'multiple' => 0,
                    ),
                    array(
                        'key' => 'field_60688e7ae99c5',
                        'label' => '书目状态',
                        'name' => 'menu_libstate_id',
                        'type' => 'taxonomy',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => array(
                            array(
                                array(
                                    'field' => 'field_60635455043ee',
                                    'operator' => '==',
                                    'value' => 'beebee_library_state',
                                ),
                            ),
                        ),
                        'wrapper' => array(
                            'width' => '15',
                            'class' => '',
                            'id' => '',
                        ),
                        'taxonomy' => 'beebee_library_state',
                        'field_type' => 'select',
                        'allow_null' => 0,
                        'add_term' => 0,
                        'save_terms' => 0,
                        'load_terms' => 0,
                        'return_format' => 'id',
                        'multiple' => 0,
                    ),
                ),
            ),
            array(
                'key' => 'field_6068978ac520a',
                'label' => '发现页头部菜单',
                'name' => 'bee_setting_faxianmenu',
                'type' => 'repeater',
                'instructions' => '可自定义菜单标题，拖动菜单位置顺序。菜单项最少1个，最多2个',
                'required' => 1,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'acfe_repeater_stylised_button' => 0,
                'collapsed' => '',
                'min' => 1,
                'max' => 2,
                'layout' => 'table',
                'button_label' => '添加新菜单',
                'sub_fields' => array(
                    array(
                        'key' => 'field_6068978ac520b',
                        'label' => '菜单项标题',
                        'name' => 'menu_title',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '20',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                    ),
                    array(
                        'key' => 'field_6068978ac520c',
                        'label' => '菜单对应内容',
                        'name' => 'menu_posttype',
                        'type' => 'select',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'choices' => array(
                            '## 内容类型' => '## 内容类型',
                            'beebee_star' => '评星',
                            'beebee_tuitui' => '推推',
                        ),
                        'default_value' => false,
                        'allow_null' => 0,
                        'multiple' => 0,
                        'ui' => 0,
                        'return_format' => 'value',
                        'ajax' => 0,
                        'placeholder' => '',
                    ),
                ),
            ),
            array(
                'key' => 'field_606898464ffcb',
                'label' => '资讯页头部菜单',
                'name' => 'bee_setting_msgmenu',
                'type' => 'repeater',
                'instructions' => '可自定义菜单标题，拖动菜单位置顺序。菜单项最少1个，最多5个',
                'required' => 1,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'acfe_repeater_stylised_button' => 0,
                'collapsed' => '',
                'min' => 1,
                'max' => 5,
                'layout' => 'table',
                'button_label' => '添加新菜单',
                'sub_fields' => array(
                    array(
                        'key' => 'field_606898464ffcc',
                        'label' => '菜单项标题',
                        'name' => 'menu_title',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '20',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                    ),
                    array(
                        'key' => 'field_606898464ffcd',
                        'label' => '菜单对应内容',
                        'name' => 'menu_posttype',
                        'type' => 'select',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'choices' => array(
                            '## 内容类型' => '## 内容类型',
                            'beebee_faq' => '问答列表',
                            'beebee_act' => '活动列表',
                            'beebee_notice' => '公告列表',
                            'post' => '文章列表',
                            '## 页面类型' => '## 页面类型',
                            'page' => '单个页面',
                        ),
                        'default_value' => false,
                        'allow_null' => 0,
                        'multiple' => 0,
                        'ui' => 0,
                        'return_format' => 'value',
                        'ajax' => 0,
                        'placeholder' => '',
                    ),
                    array(
                        'key' => 'field_606899024ffce',
                        'label' => '选择页面',
                        'name' => 'menu_pageid',
                        'type' => 'post_object',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => array(
                            array(
                                array(
                                    'field' => 'field_606898464ffcd',
                                    'operator' => '==',
                                    'value' => 'beebee_page',
                                ),
                            ),
                        ),
                        'wrapper' => array(
                            'width' => '15',
                            'class' => '',
                            'id' => '',
                        ),
                        'post_type' => array(
                            0 => 'page',
                        ),
                        'taxonomy' => '',
                        'allow_null' => 0,
                        'multiple' => 0,
                        'return_format' => 'id',
                        'save_custom' => 0,
                        'save_post_status' => 'publish',
                        'acfe_bidirectional' => array(
                            'acfe_bidirectional_enabled' => '0',
                        ),
                        'ui' => 1,
                    ),
                ),
            ),
            array(
                'key' => 'field_6068a83866e84',
                'label' => '主页侧栏导航',
                'name' => 'bee_setting_wrapleft',
                'type' => 'repeater',
                'instructions' => '可自定义菜单标题，拖动菜单位置顺序。菜单项最少1个，最多5个',
                'required' => 1,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'acfe_repeater_stylised_button' => 0,
                'collapsed' => '',
                'min' => 1,
                'max' => 5,
                'layout' => 'table',
                'button_label' => '添加新菜单',
                'sub_fields' => array(
                    array(
                        'key' => 'field_6068a83866e85',
                        'label' => '菜单项标题',
                        'name' => 'menu_title',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '20',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                    ),
                    array(
                        'key' => 'field_6068a83866e86',
                        'label' => '菜单对应内容',
                        'name' => 'menu_posttype',
                        'type' => 'select',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'choices' => array(
                            '## 内容类型' => '## 内容类型',
                            'beebee_mode_custom_img' => '弹出图片',
                            'beebee_mode_custom_wx' => '跳转小程序',
                            'beebee_mode_custom_link' => '跳转页面',
                        ),
                        'default_value' => false,
                        'allow_null' => 0,
                        'multiple' => 0,
                        'ui' => 0,
                        'return_format' => 'value',
                        'ajax' => 0,
                        'placeholder' => '',
                    ),
                    array(
                        'key' => 'field_6068a83866e87',
                        'label' => '弹出图片',
                        'name' => 'menu_custom_img',
                        'type' => 'image',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => array(
                            array(
                                array(
                                    'field' => 'field_6068a83866e86',
                                    'operator' => '==',
                                    'value' => 'beebee_mode_custom_img',
                                ),
                            ),
                        ),
                        'wrapper' => array(
                            'width' => '15',
                            'class' => '',
                            'id' => '',
                        ),
                        'uploader' => '',
                        'acfe_thumbnail' => 0,
                        'return_format' => 'url',
                        'preview_size' => 'medium',
                        'min_width' => '',
                        'min_height' => '',
                        'min_size' => '',
                        'max_width' => '',
                        'max_height' => '',
                        'max_size' => '',
                        'mime_types' => '',
                        'library' => 'all',
                    ),
                    array(
                        'key' => 'field_6068aa5466e88',
                        'label' => '跳转AppID',
                        'name' => 'menu_custom_appid',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => array(
                            array(
                                array(
                                    'field' => 'field_6068a83866e86',
                                    'operator' => '==',
                                    'value' => 'beebee_mode_custom_wx',
                                ),
                            ),
                        ),
                        'wrapper' => array(
                            'width' => '15',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                    ),
                    array(
                        'key' => 'field_6068aa9a66e89',
                        'label' => '跳转path',
                        'name' => 'menu_custom_link',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => array(
                            array(
                                array(
                                    'field' => 'field_6068a83866e86',
                                    'operator' => '==',
                                    'value' => 'beebee_mode_custom_link',
                                ),
                            ),
                            array(
                                array(
                                    'field' => 'field_6068a83866e86',
                                    'operator' => '==',
                                    'value' => 'beebee_mode_custom_wx',
                                ),
                            ),
                        ),
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                    ),
                ),
            ),
            array(
                'key' => 'field_606352ef5c16c',
                'label' => '布局设置',
                'name' => '',
                'type' => 'tab',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'placement' => 'top',
                'endpoint' => 0,
            ),
            array(
                'key' => 'field_6068af49e7f31',
                'label' => '风格',
                'name' => 'bee_setting_style',
                'type' => 'group',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'layout' => 'row',
                'acfe_seamless_style' => 0,
                'acfe_group_modal' => 0,
                'sub_fields' => array(
                    array(
                        'key' => 'field_6068ac4e9a557',
                        'label' => '小程序风格',
                        'name' => 'style_layout',
                        'type' => 'radio',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'choices' => array(
                            1 => '卡片式',
                        ),
                        'allow_null' => 0,
                        'other_choice' => 0,
                        'default_value' => '',
                        'layout' => 'horizontal',
                        'return_format' => 'value',
                        'save_other_choice' => 0,
                    ),
                    array(
                        'key' => 'field_6068ae059a559',
                        'label' => '主色系',
                        'name' => 'style_maincolor',
                        'type' => 'color_picker',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '#1878F3',
                    ),
                ),
            ),
            array(
                'key' => 'field_6068af9ae7f32',
                'label' => '样式',
                'name' => 'bee_setting_layout',
                'type' => 'group',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'layout' => 'row',
                'acfe_seamless_style' => 0,
                'acfe_group_modal' => 0,
                'sub_fields' => array(
                    array(
                        'key' => 'field_6068b011e7f33',
                        'label' => '卡片列表',
                        'name' => 'style_cardlist',
                        'type' => 'group',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'layout' => 'table',
                        'acfe_seamless_style' => 0,
                        'acfe_group_modal' => 0,
                        'sub_fields' => array(
                            array(
                                'key' => 'field_6068b044e7f34',
                                'label' => '外边距',
                                'name' => 'card_margin',
                                'type' => 'text',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'default_value' => 32,
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => 'rpx',
                                'maxlength' => '',
                            ),
                            array(
                                'key' => 'field_6068b085e7f35',
                                'label' => '内边距',
                                'name' => 'card_padding',
                                'type' => 'text',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'default_value' => 28,
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => 'rpx',
                                'maxlength' => '',
                            ),
                            array(
                                'key' => 'field_6068b0bce7f36',
                                'label' => '圆角',
                                'name' => 'card_radius',
                                'type' => 'text',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'default_value' => 20,
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => 'rpx',
                                'maxlength' => '',
                            ),
                        ),
                    ),
                    array(
                        'key' => 'field_6068b1e3f4e9b',
                        'label' => '弹层',
                        'name' => 'style_popup',
                        'type' => 'group',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'layout' => 'table',
                        'acfe_seamless_style' => 0,
                        'acfe_group_modal' => 0,
                        'sub_fields' => array(
                            array(
                                'key' => 'field_6068b1e3f4e9c',
                                'label' => '毛玻璃效果',
                                'name' => 'popup_bgfilter',
                                'type' => 'text',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'default_value' => 5,
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => 'px',
                                'maxlength' => '',
                            ),
                            array(
                                'key' => 'field_6068b1e3f4e9d',
                                'label' => '内边距',
                                'name' => 'popup_padding',
                                'type' => 'text',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'default_value' => 28,
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => 'rpx',
                                'maxlength' => '',
                            ),
                            array(
                                'key' => 'field_6068b1e3f4e9e',
                                'label' => '圆角',
                                'name' => 'pop_radius',
                                'type' => 'text',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'default_value' => 32,
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => 'rpx',
                                'maxlength' => '',
                            ),
                        ),
                    ),
                    array(
                        'key' => 'field_6068b369991d4',
                        'label' => '书籍',
                        'name' => 'style_booklist',
                        'type' => 'group',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'layout' => 'table',
                        'acfe_seamless_style' => 0,
                        'acfe_group_modal' => 0,
                        'sub_fields' => array(
                            array(
                                'key' => 'field_6068b369991d5',
                                'label' => '宽度比',
                                'name' => 'book_width',
                                'type' => 'text',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'default_value' => 350,
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '%',
                                'maxlength' => '',
                            ),
                            array(
                                'key' => 'field_6068b369991d6',
                                'label' => '高度比',
                                'name' => 'book_height',
                                'type' => 'text',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'default_value' => 220,
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '%',
                                'maxlength' => '',
                            ),
                            array(
                                'key' => 'field_6068b369991d7',
                                'label' => '圆角比',
                                'name' => 'book_radius',
                                'type' => 'text',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'default_value' => '0.5',
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '%',
                                'maxlength' => '',
                            ),
                            array(
                                'key' => 'field_6068b45aacaa0',
                                'label' => '叠加图',
                                'name' => 'book_afterimg',
                                'type' => 'text',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'default_value' => '',
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                                'maxlength' => '',
                            ),
                        ),
                    ),
                    array(
                        'key' => 'field_6068b5471d161',
                        'label' => '大字号',
                        'name' => 'style_fontsize_hero',
                        'type' => 'group',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'layout' => 'table',
                        'acfe_seamless_style' => 0,
                        'acfe_group_modal' => 0,
                        'sub_fields' => array(
                            array(
                                'key' => 'field_6068b5471d162',
                                'label' => 'H1',
                                'name' => 'font-h1',
                                'type' => 'text',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'default_value' => 52,
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => 'rpx',
                                'maxlength' => '',
                            ),
                            array(
                                'key' => 'field_6068b5471d163',
                                'label' => 'H2',
                                'name' => 'font-h2',
                                'type' => 'text',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'default_value' => 44,
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => 'rpx',
                                'maxlength' => '',
                            ),
                            array(
                                'key' => 'field_6068b5471d164',
                                'label' => 'H3',
                                'name' => 'font-h3',
                                'type' => 'text',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'default_value' => 34,
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => 'rpx',
                                'maxlength' => '',
                            ),
                            array(
                                'key' => 'field_6068b5471d165',
                                'label' => 'H4',
                                'name' => 'font-h4',
                                'type' => 'text',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'default_value' => 30,
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => 'rpx',
                                'maxlength' => '',
                            ),
                        ),
                    ),
                    array(
                        'key' => 'field_6068b69afa5dc',
                        'label' => '常用字号',
                        'name' => 'style_fontsize',
                        'type' => 'group',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'layout' => 'table',
                        'acfe_seamless_style' => 0,
                        'acfe_group_modal' => 0,
                        'sub_fields' => array(
                            array(
                                'key' => 'field_6068b69afa5e1',
                                'label' => 'H5',
                                'name' => 'font-h5',
                                'type' => 'text',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'default_value' => 28,
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => 'rpx',
                                'maxlength' => '',
                            ),
                            array(
                                'key' => 'field_6068b69afa5e2',
                                'label' => 'H6',
                                'name' => 'font-h6',
                                'type' => 'text',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'default_value' => 26,
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => 'rpx',
                                'maxlength' => '',
                            ),
                            array(
                                'key' => 'field_6068b69afa5e3',
                                'label' => 'H7',
                                'name' => 'font-h7',
                                'type' => 'text',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'default_value' => 22,
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => 'rpx',
                                'maxlength' => '',
                            ),
                            array(
                                'key' => 'field_6068b69afa5e4',
                                'label' => 'H8',
                                'name' => 'font-h8',
                                'type' => 'text',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'default_value' => 16,
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => 'rpx',
                                'maxlength' => '',
                            ),
                        ),
                    ),
                ),
            ),
            array(
                'key' => 'field_6063532b393e4',
                'label' => '通用设置',
                'name' => '',
                'type' => 'tab',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'placement' => 'top',
                'endpoint' => 0,
            ),
            array(
                'key' => 'field_6068b834de021',
                'label' => '安全性',
                'name' => 'bee_setting_safe',
                'type' => 'group',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'layout' => 'row',
                'acfe_seamless_style' => 0,
                'acfe_group_modal' => 0,
                'sub_fields' => array(
                    array(
                        'key' => 'field_6068b834de022',
                        'label' => '自定义restapi路径',
                        'name' => 'safe_restapi',
                        'type' => 'text',
                        'instructions' => '防止RestAPI内容外露，请重新命名并更新保存【固定连接】设置',
                        'required' => 1,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => 'wp-json',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                    ),
                    array(
                        'key' => 'field_6068b834de023',
                        'label' => '发布模式',
                        'name' => 'safe_mode',
                        'type' => 'true_false',
                        'instructions' => '启用后会隐藏小程序中的音视频、下载、评论等模块，建议个人资质小程序提交审核时开启',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'message' => '',
                        'default_value' => 0,
                        'ui' => 1,
                        'ui_on_text' => '启用',
                        'ui_off_text' => '关闭',
                    ),
                ),
            ),
            array(
                'key' => 'field_606355537bbd8',
                'label' => '广告设置',
                'name' => '',
                'type' => 'tab',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'placement' => 'top',
                'endpoint' => 0,
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'options_page',
                    'operator' => '==',
                    'value' => 'appbeebee-theme-setting',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => true,
        'description' => '',
        'config_save_path' => 'default',
    ));
    
    acf_add_local_field_group(array(
        'key' => 'group_605353ab24226',
        'title' => '书目字段',
        'fields' => array(
            array(
                'key' => 'field_605487657e809',
                'label' => '书籍基础字段',
                'name' => 'bee_book_basegroup',
                'type' => 'group',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'layout' => 'block',
                'sub_fields' => array(
                    array(
                        'key' => 'field_605353beb97ff',
                        'label' => 'ISBN',
                        'name' => 'bee_book_isbn',
                        'type' => 'text',
                        'instructions' => '填写书籍ISBN可自动获取书籍其他数据',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '<div	id="bookautomsg"><span>输入ISBN自动获取书籍信息</span></div>',
                        'maxlength' => '',
                        'show_column' => 0,
                        'show_column_sortable' => 0,
                        'show_column_weight' => 400,
                        'allow_quickedit' => 0,
                        'allow_bulkedit' => 0,
                    ),
                    array(
                        'key' => 'field_605354fbb9802',
                        'label' => '书名',
                        'name' => 'bee_book_title',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                    ),
                    array(
                        'key' => 'field_60560dfa11460',
                        'label' => '豆瓣资源',
                        'name' => 'bee_book_covergroup',
                        'type' => 'group',
                        'instructions' => '点击打开链接后页面提示无权限“You do not have permission..”，在地址栏回车可查看',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'layout' => 'table',
                        'sub_fields' => array(
                            array(
                                'key' => 'field_60562474e84b9',
                                'label' => '豆瓣页',
                                'name' => 'bee_book_dbpage',
                                'type' => 'url',
                                'instructions' => '<a class="beetips" href="#" target="_blank" style="display:none;">打开链接</a>',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'default_value' => '',
                                'placeholder' => '',
                            ),
                            array(
                                'key' => 'field_60544be8202b0',
                                'label' => '大封面',
                                'name' => 'bee_book_dbcover_l',
                                'type' => 'url',
                                'instructions' => '<a class="beetips" href="#" target="_blank" style="display:none;">打开链接</a>',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'default_value' => '',
                                'placeholder' => '',
                            ),
                            array(
                                'key' => 'field_60560e5211461',
                                'label' => '小封面',
                                'name' => 'bee_book_dbcover_s',
                                'type' => 'url',
                                'instructions' => '<a class="beetips" href="#" target="_blank" style="display:none;">打开链接</a>',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'default_value' => '',
                                'placeholder' => '',
                            ),
                        ),
                    ),
                    array(
                        'key' => 'field_60535486b9800',
                        'label' => '豆瓣ID',
                        'name' => 'bee_book_dbid',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                    ),
                ),
            ),
            array(
                'key' => 'field_6054866a7e807',
                'label' => '书籍信息字段',
                'name' => 'bee_book_msggroup',
                'type' => 'group',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'layout' => 'table',
                'sub_fields' => array(
                    array(
                        'key' => 'field_605354d5b9801',
                        'label' => '豆瓣评分',
                        'name' => 'bee_book_dbscore',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'admin_column_enabled' => 1,
                        'admin_column_post_types' => array(
                            0 => 'beebee_library',
                        ),
                        'admin_column_taxonomies' => '',
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                    ),
                    array(
                        'key' => 'field_60535747b9804',
                        'label' => '作者',
                        'name' => 'bee_book_author',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                    ),
                    array(
                        'key' => 'field_60535764b9805',
                        'label' => '译者',
                        'name' => 'bee_book_translator',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                    ),
                    array(
                        'key' => 'field_60535544b9803',
                        'label' => '售价',
                        'name' => 'bee_book_price',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                    ),
                    array(
                        'key' => 'field_6053577eb9806',
                        'label' => '出版社',
                        'name' => 'bee_book_publisher',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                    ),
                    array(
                        'key' => 'field_605357a3b9807',
                        'label' => '出版年',
                        'name' => 'bee_book_published',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                    ),
                    array(
                        'key' => 'field_605357b8b9808',
                        'label' => '页数',
                        'name' => 'bee_book_page',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                    ),
                    array(
                        'key' => 'field_605357ddb9809',
                        'label' => '装帧',
                        'name' => 'bee_book_designed',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                    ),
                ),
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'beebee_library',
                ),
            ),
        ),
        'menu_order' => 1,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'left',
        'instruction_placement' => 'field',
        'hide_on_screen' => '',
        'active' => true,
        'description' => '',
    ));
    
    acf_add_local_field_group(array(
        'key' => 'group_605359e3d1b16',
        'title' => '颜色管理',
        'fields' => array(
            array(
                'key' => 'field_60535a03413aa',
                'label' => '背景色',
                'name' => 'bee_book_background',
                'type' => 'color_picker',
                'instructions' => '每本书籍可设置一个贴近封面的颜色。不选择默认为深灰色。',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '#4c4845',
                'show_column' => 1,
                'show_column_sortable' => 1,
                'show_column_weight' => 400,
                'allow_quickedit' => 0,
                'allow_bulkedit' => 0,
            ),
            array(
                'key' => 'field_60535a8b413ab',
                'label' => '色系',
                'name' => 'bee_book_pagestyle',
                'type' => 'radio',
                'instructions' => '根据选择的背景色调整这里的选项。深色指背景色选择深色，前端界面文字等元素即为白色，反之同理。',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'choices' => array(
                    'blackbg' => '深色',
                    'whitebg' => '浅色',
                ),
                'allow_null' => 0,
                'other_choice' => 0,
                'default_value' => 'blackbg',
                'layout' => 'horizontal',
                'return_format' => 'value',
                'show_column' => 0,
                'show_column_sortable' => 0,
                'show_column_weight' => 1000,
                'allow_quickedit' => 0,
                'allow_bulkedit' => 0,
                'save_other_choice' => 0,
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'beebee_library',
                ),
            ),
        ),
        'menu_order' => 2,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'left',
        'instruction_placement' => 'field',
        'hide_on_screen' => '',
        'active' => true,
        'description' => '',
    ));
    
    acf_add_local_field_group(array(
        'key' => 'group_60535c3fee017',
        'title' => '资源管理',
        'fields' => array(
            array(
                'key' => 'field_60535c48a94c3',
                'label' => '书籍共享形式',
                'name' => 'bee_book_sharetype',
                'type' => 'checkbox',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'choices' => array(
                    'borrow' => '可借阅',
                    'download' => '可下载',
                    'onread' => '可PDF阅读',
                ),
                'allow_custom' => 0,
                'default_value' => array(
                    0 => 'borrow',
                ),
                'layout' => 'horizontal',
                'toggle' => 0,
                'return_format' => 'value',
                'show_column' => 1,
                'show_column_weight' => 400,
                'allow_quickedit' => 0,
                'allow_bulkedit' => 0,
                'save_custom' => 0,
            ),
            array(
                'key' => 'field_605362dac8923',
                'label' => 'PDF上传',
                'name' => 'bee_book_pdf',
                'type' => 'file',
                'instructions' => '仅支持PDF格式文件，小程序优先获取上传的文件地址，如没有会获取PDF引用地址。',
                'required' => 0,
                'conditional_logic' => array(
                    array(
                        array(
                            'field' => 'field_60535c48a94c3',
                            'operator' => '==',
                            'value' => 'onread',
                        ),
                    ),
                ),
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'return_format' => 'url',
                'library' => 'uploadedTo',
                'min_size' => '',
                'max_size' => '',
                'mime_types' => 'pdf',
            ),
            array(
                'key' => 'field_6053636bc8924',
                'label' => 'PDF引用',
                'name' => 'bee_book_pdflink',
                'type' => 'url',
                'instructions' => '可填写外网文件地址，但需提交域名到微信公众平台request合法域名、downloadFile合法域名中。',
                'required' => 0,
                'conditional_logic' => array(
                    array(
                        array(
                            'field' => 'field_60535c48a94c3',
                            'operator' => '==',
                            'value' => 'onread',
                        ),
                    ),
                ),
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
            ),
            array(
                'key' => 'field_60535f38a94c6',
                'label' => '下载内容',
                'name' => 'bee_book_download',
                'type' => 'textarea',
                'instructions' => '下方下载权限取消勾选则所有人可见。支持HTML，如果不会代码按下方格式填写，注意都是半角冒号：（名称+冒号+空格+链接内容+空格+名称+冒号+空格+提取码内容）
    <pre style="padding:10px; border:11px solid #E1E1E;background-color:#F9F9F9;">链接: https://pan.baidu.com/s/1pyE49zSmiCEAqEX4RBhp2w 提取码: n37f</pre>',
                'required' => 0,
                'conditional_logic' => array(
                    array(
                        array(
                            'field' => 'field_60535c48a94c3',
                            'operator' => '==',
                            'value' => 'download',
                        ),
                    ),
                ),
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'maxlength' => '',
                'rows' => 3,
                'new_lines' => '',
                'show_column' => 0,
                'show_column_weight' => 1000,
                'allow_quickedit' => 0,
                'allow_bulkedit' => 0,
            ),
            array(
                'key' => 'field_60536501460eb',
                'label' => '下载权限',
                'name' => 'bee_book_downloadneed',
                'type' => 'checkbox',
                'instructions' => '如果勾选了看视频广告，但小程序未开通流量主不会显示广告',
                'required' => 0,
                'conditional_logic' => array(
                    array(
                        array(
                            'field' => 'field_60535c48a94c3',
                            'operator' => '==',
                            'value' => 'download',
                        ),
                    ),
                ),
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'choices' => array(
                    'login' => '会员登录',
                    'videoads' => '看视频广告',
                ),
                'allow_custom' => 0,
                'default_value' => array(
                    0 => 'login',
                ),
                'layout' => 'horizontal',
                'toggle' => 0,
                'return_format' => 'value',
                'show_column' => 0,
                'show_column_weight' => 1000,
                'allow_quickedit' => 1,
                'allow_bulkedit' => 1,
                'save_custom' => 0,
            ),
            array(
                'key' => 'field_60536c2f6635f',
                'label' => '下载说明',
                'name' => 'bee_book_downloadmsg',
                'type' => 'text',
                'instructions' => '对该本书下载时的独立说明。如果是通用说明请至爱书者主题插件处[下载说明]处统一填写。一般填写版权归属声明。',
                'required' => 0,
                'conditional_logic' => array(
                    array(
                        array(
                            'field' => 'field_60535c48a94c3',
                            'operator' => '==',
                            'value' => 'download',
                        ),
                    ),
                ),
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
            ),
            array(
                'key' => 'field_60535d5aa94c4',
                'label' => '借阅费用',
                'name' => 'bee_book_rent',
                'type' => 'text',
                'instructions' => '填写数字，默认0表示免费',
                'required' => 0,
                'conditional_logic' => array(
                    array(
                        array(
                            'field' => 'field_60535c48a94c3',
                            'operator' => '==',
                            'value' => 'borrow',
                        ),
                    ),
                ),
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => 0,
                'placeholder' => '',
                'prepend' => '¥',
                'append' => '单位：元/月',
                'maxlength' => '',
                'show_column' => 0,
                'show_column_sortable' => 0,
                'show_column_weight' => 1000,
                'allow_quickedit' => 0,
                'allow_bulkedit' => 0,
            ),
            array(
                'key' => 'field_60535e9aa94c5',
                'label' => '借阅库存',
                'name' => 'bee_book_stock',
                'type' => 'radio',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => array(
                    array(
                        array(
                            'field' => 'field_60535c48a94c3',
                            'operator' => '==',
                            'value' => 'borrow',
                        ),
                    ),
                ),
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'choices' => array(
                    -1 => '下架',
                    0 => '无库存',
                    1 => '可借阅',
                ),
                'allow_null' => 0,
                'other_choice' => 0,
                'default_value' => 1,
                'layout' => 'horizontal',
                'return_format' => 'value',
                'show_column' => 0,
                'show_column_sortable' => 0,
                'show_column_weight' => 1000,
                'allow_quickedit' => 1,
                'allow_bulkedit' => 1,
                'save_other_choice' => 0,
            ),
            array(
                'key' => 'field_60536ba36635e',
                'label' => '借阅说明',
                'name' => 'bee_book_borrowmsg',
                'type' => 'text',
                'instructions' => '对该本书借阅时的独立说明。如果是通用说明请至爱书者主题插件处[借阅说明]处统一填写。',
                'required' => 0,
                'conditional_logic' => array(
                    array(
                        array(
                            'field' => 'field_60535c48a94c3',
                            'operator' => '==',
                            'value' => 'borrow',
                        ),
                    ),
                ),
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'beebee_library',
                ),
            ),
        ),
        'menu_order' => 3,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'left',
        'instruction_placement' => 'field',
        'hide_on_screen' => '',
        'active' => true,
        'description' => '',
    ));
    
    acf_add_local_field_group(array(
        'key' => 'group_60537154ed983',
        'title' => '专题字段',
        'fields' => array(
            array(
                'key' => 'field_6053717734673',
                'label' => '选择书目',
                'name' => 'bee_to_library',
                'type' => 'relationship',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'post_type' => array(
                    0 => 'beebee_library',
                ),
                'taxonomy' => '',
                'filters' => array(
                    0 => 'search',
                ),
                'elements' => array(
                    0 => 'featured_image',
                ),
                'min' => '',
                'max' => '',
                'return_format' => 'id',
            ),
            array(
                'key' => 'field_60564ee356be9',
                'label' => '专题封面形式',
                'name' => 'bee_topic_coverstyle',
                'type' => 'button_group',
                'instructions' => '你可以定义单个专题列表的封面样式。默认使用关联书籍的封面组图，你可以定义一张特色图片作为专题封面。特色图片尺寸最佳为500x800px',
                'required' => 1,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'choices' => array(
                    1 => '使用书籍组图',
                    2 => '使用特色图',
                ),
                'allow_null' => 0,
                'default_value' => 1,
                'layout' => 'horizontal',
                'return_format' => 'value',
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'beebee_topic',
                ),
            ),
        ),
        'menu_order' => 4,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'left',
        'instruction_placement' => 'field',
        'hide_on_screen' => '',
        'active' => true,
        'description' => '',
    ));
    
    acf_add_local_field_group(array(
        'key' => 'group_605430b9b330d',
        'title' => '语录字段',
        'fields' => array(
            array(
                'key' => 'field_60543dfc17ec7',
                'label' => '语录内容',
                'name' => 'bee_quot_group',
                'type' => 'group',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'layout' => 'table',
                'sub_fields' => array(
                    array(
                        'key' => 'field_60543f2617ec9',
                        'label' => '语录文摘',
                        'name' => 'bee_quot_cnt',
                        'type' => 'textarea',
                        'instructions' => '语录不要超过300字',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                        'maxlength' => 300,
                        'rows' => 11,
                        'new_lines' => 'br',
                    ),
                    array(
                        'key' => 'field_60543eae17ec8',
                        'label' => '选择书目',
                        'name' => 'bee_to_library',
                        'type' => 'relationship',
                        'instructions' => '每篇语录仅可选择一本书籍',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'post_type' => array(
                            0 => 'beebee_library',
                        ),
                        'taxonomy' => '',
                        'filters' => array(
                            0 => 'search',
                        ),
                        'elements' => array(
                            0 => 'featured_image',
                        ),
                        'min' => '',
                        'max' => 1,
                        'return_format' => 'id',
                    ),
                ),
            ),
            array(
                'key' => 'field_605650df12bea',
                'label' => '语录封面形式',
                'name' => 'bee_quot_coverstyle',
                'type' => 'button_group',
                'instructions' => '你可以定义单个语录列表的封面样式。默认使用关联书籍的封面图片，你可以定义一张特色图片作为语录封面。特色图片尺寸最佳为500x800px',
                'required' => 1,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'choices' => array(
                    1 => '使用书籍封面',
                    2 => '使用特色图',
                ),
                'allow_null' => 0,
                'default_value' => 1,
                'layout' => 'horizontal',
                'return_format' => 'value',
            ),
            array(
                'key' => 'field_60543aaa17ec6',
                'label' => '语音合成',
                'name' => 'bee_quot_radio',
                'type' => 'textarea',
                'instructions' => '小程序默认使用微信同声传译插件进行播放语音。
    支持使用标签组合语音内容：%quotcnt%(语录内容)、%sitename%(网站标题)、%postname%(文章标题)、%date%(发布时间)、%author%(文章作者)',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '%quotcnt%，%sitename%为您朗读',
                'placeholder' => '',
                'maxlength' => '',
                'rows' => 2,
                'new_lines' => '',
            ),
            array(
                'key' => 'field_605431845fad1',
                'label' => '语音状态',
                'name' => 'bee_quot_audiostate',
                'type' => 'text',
                'instructions' => '此处不要修改',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => 'input-disabled',
                    'id' => '',
                ),
                'default_value' => 'false',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'beebee_quot',
                ),
            ),
        ),
        'menu_order' => 6,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'left',
        'instruction_placement' => 'field',
        'hide_on_screen' => '',
        'active' => true,
        'description' => '',
    ));
    
    endif;